name: 'Migration testing'

on:
  workflow_dispatch: {}
  workflow_call: {}


jobs:
  create-index-legacy-paid:
    name: Migration testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - asia-southeast1-gcp
          - asia-northeast1-gcp
          - eu-west1-gcp
          - eu-west4-gcp
          - northamerica-northeast1-gcp
          - us-central1-gcp
          - us-east1-gcp
          - us-east4-gcp
          - us-west1-gcp
          - us-west4-gcp
          - eastus-azure
          - us-east-1-aws

        # - gcp-starter
        # - asia-southeast1-gcp-free
        # - us-west1-gcp-free
        # - us-west4-gcp-free

          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create on legacy control plane
        id: create-legacy
        uses: ./.github/actions/create-index-legacy
        with:
          PINECONE_API_KEY: ${{ secrets.V3MIGRATION_API_KEY__ONE_KEY_MANY_ENVS }}
          PINECONE_ENVIRONMENT: ${{ matrix.env }}
          pinecone_client_version: 2.2.4
          index_name_prefix: py-migration
          dimension: 1536
          metric: cosine

      - name: Inspect on GCPS
        id: inspect-gcps
        uses: ./.github/actions/test-legacy-index
        with:
          PINECONE_API_KEY: ${{ secrets.V3MIGRATION_API_KEY__ONE_KEY_MANY_ENVS }}
          PINECONE_ENVIRONMENT: ${{ matrix.env }}
          pinecone_client_version: 3.0.0.dev8
          index_name: ${{ steps.create-legacy.outputs.index_name }}

  cleanup:
    if: always()
    needs: [create-index-legacy-paid]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Delete all indexes
        uses: ./.github/actions/delete-all-indexes
        with:
          PINECONE_API_KEY: ${{ secrets.V3MIGRATION_API_KEY__ONE_KEY_MANY_ENVS }}
          pinecone_client_version: 3.0.0.dev8